app/models.py
from . import mongo_db
from mongoengine.queryset import queryset_manager


class Post(mongo_db.Document):
    _id = mongo_db.ObjectIdField(required=True)
    topic = mongo_db.StringField()
    title = mongo_db.StringField(max_length=255, required=True)
    media = mongo_db.StringField()
    content = mongo_db.StringField(required=True)
    published_at = mongo_db.DateTimeField()
    created_time = mongo_db.DateTimeField()
    image_urls = mongo_db.ListField(mongo_db.StringField())
    keywords = mongo_db.ListField(mongo_db.StringField())
    id = mongo_db.StringField(required=True)

    url = mongo_db.StringField()
    categories = mongo_db.IntField()
    origin_content = mongo_db.StringField(required=True)
    meta = {'collection': 'news'}

    @queryset_manager
    def objects(cls, queryset):
        return queryset.order_by("-published_at")

    def __unicode__(self):
        return self.title

    def __repr__(self):
        return '<Post %r>' % self.title

app/__init__.py
# -*- coding:utf-8 -*-
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from config import config
from flask_moment import Moment
from flask_mongoengine import MongoEngine
import datetime

bootstrap = Bootstrap()
moment = Moment()
mongo_db = MongoEngine()


# 自定义jinjia2的过滤器
def transform_timestamp(timestamp):
    d = datetime.datetime.fromtimestamp(timestamp)
    result = d.strftime("%Y-%m-%d")
    return result


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    mongo_db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # 注册jinjia2的自定义过滤器
    env = app.jinja_env
    env.filters['transform_timestamp'] = transform_timestamp

    return app

app/main/__init__.py
# -*- coding:utf-8 -*-

from flask import Blueprint

main = Blueprint('main', __name__)
from . import views, errors

app/main/views.py
# -*- coding:utf-8 -*-
from flask import render_template, request, redirect
from . import main
from ..models import Post


@main.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    pagination = Post.objects.paginate(page=page, per_page=10)
    posts = pagination.items
    return render_template('index.html', posts=posts, pagination=pagination)


@main.route('/topic/<topic>')
def topic(topic):
    page = request.args.get('page', 1, type=int)
    todo = Post.objects(topic=topic)
    pagination = todo.paginate(page=page, per_page=10)
    posts = pagination.items
    return render_template('topic.html', posts=posts, topic=topic, pagination=pagination)


@main.route('/analysis', methods=['GET', 'POST'])
def analysis():
    return redirect("https://datav.aliyun.com/share/d0a7559e0e5d8ab9d64a51182c01e804")


@main.route('/<topic>/<id>', methods=['GET', 'POST'])
def post(topic, id):
    post = Post.objects.get_or_404(_id=id)
    return render_template('post.html', post=post)

app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination pagination-minimal" style="background-color:#B1BAB4" align="center">
    <li {% if not pagination.has_prev %} class="disabled previous" {% else %} class="previous" {% endif %} >
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
            page = pagination.page - 1, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled next" {% else %} class="next" {% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint,
            page = pagination.page + 1, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/templates/_posts.html
{% for post in posts %}
    <article class="article the-font" style="box-shadow: rgb(167, 163, 163) 5px 5px 20px;background:#fffffc;">
        <a href="{{ url_for('.post', topic = post.topic,id=post._id) }}"><h3 style="color:#34495E">{{ post.title }}</h3></a>
        <p style="padding-left:20px;">
            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
            <a> {{ post.media }}</a> &nbsp
            <small>
                <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                <span style="color:#8C8C8C;"> {{ post.published_at | transform_timestamp }}</span>
            </small>
            <a href="{{ url_for('main.topic',topic=post.topic) }}" style="float:right">
                <span class="label label-success"><i class="fa fa-paperclip"
                                                     aria-hidden="true"></i> {{ post.topic }}</span>
            </a>
        </p>


        <div style="border-top:1px solid #EBEBEB;padding:20px 5px;margin-bottom:20px;">
            <span style="float:right;">
                <a href="{{ url_for('.post', topic = post.topic,id=post._id) }}">
                    <button class="btn  btn-inverse"><i class="fa fa-chevron-circle-down"
                                                        aria-hidden="true"></i> 详情</button>
                </a>
            </span>
        </div>
    </article>
{% endfor %}

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block html_attribs %} lang="en"{% endblock html_attribs %}
{% block title %}INTERNATIONAL NEWS{% endblock %}

{% block head %}
    {{ super() }}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="{{ url_for('static', filename = 'myicon.ico') }}" type="imge/x-icon">
    <link rel="icon" href="{{ url_for('static', filename = 'myicon.ico') }}" type="imge/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mystyle.css') }}">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/flat-ui/2.3.0/css/flat-ui.min.css" rel="stylesheet">
    <style type="text/css">
        h1 {
            font-size: 50px;
        }

        h2 {
            font-size: 40px;
        }

        h3 {
            font-size: 30px;
        }

        p {
            font-size: 15px;
        }

        blockquote p {
            font-size: 17px;
        }

        body {
            font-size: 15px;
            background-color: #d4dcd6;
        }
    </style>
{% endblock %}

{% block navbar %}
    <nav class="navbar-default navbar-Amethyst" style="padding:50px 0px;background:#d4dcd6;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
                    <span class="sr-only">Toggle navigation</span>
                </button>
                <a class="navbar-brand" href="/">NEWS</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-01">
                <ul class="nav navbar-nav">
                    <li><a href="/topic/World">WORLD</a></li>
                    <li><a href="/topic/Business">BUSINESS</a></li>
                    <li><a href="/topic/Sport">SPORT</a></li>
                    <li><a href="/topic/Technology">TECHNOLOGY</a></li>
                    <li><a href="/topic/Lifestyle">LIFESTYLE</a></li>
                    <li><a href="/topic/Health">HEALTH</a></li>
                    <li><a href="/analysis">ANALYSIS</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    {% block page_bottom %}{% endblock %}

    {% block page_content %}{% endblock %}
    <div style="background:#426579 none repeat scroll 0% 0%;color:#BFC9D3">
        <div class="container">
            <div class="row" style="padding-top:30px;">
                <div class="col-md-7">
                    <h5 style="margin-bottom:15px;margin-left:18px;"><strong>ABOUT</strong></h5>
                    <p style="padding:10px 150px 10px 20px"><strong>INTERNATIONAL NEWS </strong>
                        &nbsp本新闻网属个人所有，不涉及商业目的。</p>
                </div>
                <div class="col-md-5">
                    <div>
                        <h5 style="margin-bottom:15px;margin-left:18px;"><strong>CONTACT ME</strong></h5>
                        <ul class="list-unstyled" style="margin-bottom:15px;margin-left:30px;">
                            <li><a href="#"><i class="fa fa-weixin" aria-hidden="true"></i> &nbsp caiyingyi902</a></li>
                            <li><a href="https://github.com/caiyingyi/news_web"><i class="fa fa-github" aria-hidden="true"></i>
                                &nbsp https://github.com/caiyingyi/news_web</a></li>
                            <li><a href="#"><i class="fa fa-envelope" aria-hidden="true" fa-5x></i> &nbsp
                                caiyingyi902@163.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-12 text-center" style="padding-top:30px;">
                    <p>
                        <small>© COPYRIGHT BY CAIYINGYI 2018</small>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

app/templates/category.html
{% extends "base.html" %}


{% block title %}{{ category }}{% endblock %}

{% block page_content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h4><i class="fa fa-paperclip" aria-hidden="true"></i> {{ category }}</h4><br/>

        </div>

    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block page_bottom %}
    <div class="jumbotron" style="padding-bottom:100px;background:#426579;">
        <div class="container">
            <h2 style="color:#E7DBDB">International NEWS</h2>
            <p class="lead" style="color:#E7DBDB">Some news from  BBC, NewsWeek, NewsAsia, UPI, FoxNews... </p>

        </div>
    </div>
{% endblock %}

{% block page_content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
            {% include '_posts.html' %}
            </div>

            {% if pagination %}
            <div  class="col-md-12">
                {{ macros.pagination_widget(pagination, '.index') }}
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

app/templates/post.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}文章{% endblock %}

{% block page_content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <article class="article the-font"
                         style="box-shadow: rgb(167, 163, 163) 5px 5px 20px;background:#fffffc;">
                    <h2>{{ post.title }}</h2>
                    <p style="padding-left:20px;">
                        <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                        <a> {{ post.media }}</a> &nbsp
                        <small>
                            <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                            <span style="color:#8C8C8C;"> {{ post.published_at | transform_timestamp }}</span>
                        </small>
                        <a href="{{ url_for('main.topic',topic=post.topic) }}" style="float:right"><span
                                class="label label-success"><i class="fa fa-paperclip"
                                                               aria-hidden="true"></i> {{ post.topic }}</span></a>
                    </p>

                    <div class="post-author">

                    </div>

                    <div class="post-body">
                        {% if post.content %}
                            {{ post.content | safe }}
                        {% else %}
                            {{ post.content }}
                        {% endif %}
                    </div>
                    <div style="border-top:1px solid #EBEBEB;padding:10px 5px;margin-top:20px;">
                    <span style="float:right">
                        <a href="/" class="btn btn-xs ">返回首页<span class=" glyphicon glyphicon-log-out"
                                                                  aria-hidden="true"></span></a>
                    </span>
                    </div>

                    <ul>
                        {% for keyword in post.keywords %}
                            <li class="presentation" style="padding-top:0px;">
                                <a><p><span
                                        style="font-size:15px;"> {{ keyword|upper }}</span>
                                </p>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </article>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/topic.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}{{ topic }}{% endblock %}

{% block page_content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h4><i class="fa fa-paperclip" aria-hidden="true"></i> {{ topic }}</h4><br/>
             {% include '_posts.html' %}
        </div>
        {% if pagination %}
        <div style="float:right">{{ macros.pagination_widget(pagination, '.topic',topic=topic) }}</div>
        {% endif %}
    </div>
</div>
{% endblock %}